services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - postgres-net
      - frontend-net
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}
      JWT_PREFIX: "Bearer "
      CORS_ORIGINS_ALLOWED: ${CORS_ORIGINS_ALLOWED}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - frontend-net
    depends_on:
      - backend
#    TODO: add envs global config
#    environment:

  postgres:
    container_name: "postgres_db"
    image: 'postgres:18'
    restart: always
    ports:
      - '5433:5432'
    networks:
      - postgres-net
    environment:
      POSTGRES_DB: book-store-postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-vol:/var/lib/postgresql

volumes:
  postgres-vol:

networks:
  postgres-net:
    driver: bridge

  frontend-net:
    driver: bridge