CREATE TABLE auth_identity
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT,
    email              VARCHAR(255),
    password_hash      VARCHAR(255),
    enabled            BOOLEAN                                 NOT NULL,
    account_non_locked BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_auth_identity PRIMARY KEY (id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    birth_date   date                                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);