CREATE TABLE doctor_profiles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_doctor_profiles PRIMARY KEY (id)
);

CREATE TABLE patient_profiles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    doctor_id BIGINT,
    CONSTRAINT pk_patient_profiles PRIMARY KEY (id)
);

ALTER TABLE doctor_profiles
    ADD CONSTRAINT uc_doctor_profiles_user UNIQUE (user_id);

ALTER TABLE patient_profiles
    ADD CONSTRAINT uc_patient_profiles_user UNIQUE (user_id);

ALTER TABLE doctor_profiles
    ADD CONSTRAINT FK_DOCTOR_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE patient_profiles
    ADD CONSTRAINT FK_PATIENT_PROFILES_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor_profiles (id);

ALTER TABLE patient_profiles
    ADD CONSTRAINT FK_PATIENT_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);