CREATE TABLE doctor_profiles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_doctor_profiles PRIMARY KEY (id)
);

CREATE TABLE patient_profiles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT,
    personal_doctor_id BIGINT,
    CONSTRAINT pk_patient_profiles PRIMARY KEY (id)
);