CREATE TABLE doctor_assignment_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id   BIGINT,
    doctor_id    BIGINT,
    status       SMALLINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    processed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_doctor_assignment_requests PRIMARY KEY (id)
);