DROP TABLE users;

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name         VARCHAR(255)                            NOT NULL,
    last_name          VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    phone_number       VARCHAR(255),
    enabled            BOOLEAN                                 NOT NULL,
    account_non_locked BOOLEAN                                 NOT NULL,
    date_of_birth      date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);