spring:
  application:
    name: backend

  datasource:
    url: ${postgres-url}
    username: ${postgres-user}
    password: ${postgres-password}

  jpa:
    hibernate:
      ddl-auto: none # TODO: change back to validate

# Configuration for open-api docs
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
  level:
    root: info
    com.wsei.healthcare: debug
    sql: trace
#    org.springframework.security.web.FilterChainProxy: trace

cors:
  allowed:
    origins: ${cors.allowed.origins}